// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNRpHUyHr1NDxXqScw5rX1-0q97SWF7sk',
    appId: '1:588446062654:web:847ef3d57d9f516eaf196f',
    messagingSenderId: '588446062654',
    projectId: 'notification-social-955e1',
    authDomain: 'notification-social-955e1.firebaseapp.com',
    storageBucket: 'notification-social-955e1.appspot.com',
    measurementId: 'G-N3V1XQKSTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC45-XY1EPa9eyq_CNkkg_gc4Ii8hCMgU',
    appId: '1:588446062654:android:1d48a80028f9064aaf196f',
    messagingSenderId: '588446062654',
    projectId: 'notification-social-955e1',
    storageBucket: 'notification-social-955e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSIzMW_--mkrBcab-WYumG-WfbJHAJ0zM',
    appId: '1:588446062654:ios:e0a7a1633dbefb7baf196f',
    messagingSenderId: '588446062654',
    projectId: 'notification-social-955e1',
    storageBucket: 'notification-social-955e1.appspot.com',
    iosClientId: '588446062654-gisi4nb5snml1kts1mc9bmlad3quo1c2.apps.googleusercontent.com',
    iosBundleId: 'vn.thomson.souldMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSIzMW_--mkrBcab-WYumG-WfbJHAJ0zM',
    appId: '1:588446062654:ios:e0a7a1633dbefb7baf196f',
    messagingSenderId: '588446062654',
    projectId: 'notification-social-955e1',
    storageBucket: 'notification-social-955e1.appspot.com',
    iosClientId: '588446062654-gisi4nb5snml1kts1mc9bmlad3quo1c2.apps.googleusercontent.com',
    iosBundleId: 'vn.thomson.souldMate',
  );
}
